#!/bin/bash

####################################################################
####    														####
####          Скрипт резервного копирования файлов.      		####
####    					          							####
####    					Версия 1.0							####
####															####
####################################################################


# ---------- ПЕРЕМЕННЫЕ ------------

# Задаём исходную директорию и директорию назначения, в виде переменных, для удобства
SOURCEDIR=/mnt/ab

# В этой переменной у нас будет день недели, по-русски в формате "05_Пятница"
DESTDIR=/srv/raid/base/0`date +%u`_`date +%A`

# Почему бы и не сформировать файл отчёта
LOGFILE=/var/log/backup/base_backup

# И сразу пишем в него заголовок
echo "Начинаем процедуру резервного копирования файлов базы. Дата:" `date +%A\,\ %x,\ %H:%M`  > $LOGFILE

# Этот файл -- флаг для Zabbix, который будет содержать 1 в случае, если были какие-либо ошибки при копировании
ZABBIX_FLAG=/var/log/backup/zabbix
echo "0" > $ZABBIX_FLAG

# ------------- КОД ---------------

# Пробуем монтировать каталог базы данных, если еще не смонтировано
grep -q AccessBase /etc/mtab
if [[ $? -eq 1 ]] ; then mount /mnt/ab ; fi

# Если по-прежнему не смонтировано, создаём сообщение об ошибке для заббикса, и больше не делаем вообще ничего
if [[ ! $? -eq 0 ]] ; then # Предыдущей командой была как раз mount, поэтому если $? не равно нулю, то у нас проблемы
    echo "Монтировать каталог базы не удалось" >> $LOGFILE
    echo "1" > $ZABBIX_FLAG
	break # Завершение программы, чтобы не делать кучу кода в ветке else
fi


if [ -d $DESTDIR ]; then rm -fr $DESTDIR ; fi # Если каталог уже есть, то удаляем его, там неактуальная копия

mkdir $DESTDIR

# Пробегаем скриптом сначала по файлам самой базы
for N in MarketN_be.mde Marketing_be.mdb MarketN_CRM_be.mde Shops_be.mdb Dohod.mde diagrams.mde ; do
# Если исходный файл вообще существует, то
	if [ -e $SOURCEDIR/$N ] ; then
		# Копируем его
		cp $SOURCEDIR/$N $DESTDIR

		# Считаем контрольную сумму исходного файла
		MD5SUM1=`md5sum -b $SOURCEDIR/$N | awk '{print $1}'`

		# И его новой копии
		MD5SUM2=`md5sum -b $DESTDIR/$N | awk '{print $1}'`

            # Сравниваем контрольные суммы, делаем соответствующие записи
        if [[ $MD5SUM1 == $MD5SUM2 ]] ; then
	        echo "Файл" $N "успешно скопирован в каталог" $DESTDIR "на сервере" >> $LOGFILE
	    else
	        echo "Контрольные суммы файлов не совпадают!" >> $LOGFILE
	        echo "1" > $ZABBIX_FLAG
        fi
	else
	    echo "Файл" $N "не найден в исходной директории!" >> $LOGFILE
	    echo "1" > $ZABBIX_FLAG
    fi
done

# Интерфейсы теперь обработаем

# Меняем директории
SOURCEDIR=$SOURCEDIR/Interface
DESTDIR=$DESTDIR/Interface

mkdir $DESTDIR

for N in Admin.mdb Log.mdb Marketing.mdb MarketN_CRM.mdb MarketN.mdb Shops.mdb Statistics.mdb ; do
    if [ -e $SOURCEDIR/$N ] ; then # Делаем всё то же самое, что и в предыдущем скрипте
        cp $SOURCEDIR/$N $DESTDIR
        MD5SUM1=`md5sum -b $SOURCEDIR/$N | awk '{print $1}'`
        MD5SUM2=`md5sum -b $DESTDIR/$N | awk '{print $1}'`

        if [[ $MD5SUM1 == $MD5SUM2 ]] ; then
            echo "Интерфейсный файл" $N "успешно скопирован в каталог" $DESTDIR "на сервере" >> $LOGFILE
        else
            echo "Контрольные суммы файлов не совпадают!" >> $LOGFILE
            echo "1" > $ZABBIX_FLAG
        fi
    else
            echo "Интерфейсный файл" $N "не найден в исходной директории!" >> $LOGFILE
            echo "1" > $ZABBIX_FLAG
    fi
done
